- vanilla_installer/defaults/users.py
- vanilla_installer/gtk/default-users.ui
added `fullname_entry` after noticing `distinst` provides `realname` and also make `btn_nxt` sensitive in ui so that it proceeds to next page only if all fields are entered.
> added fullname in users

- po/vanilla-installer.pot
Link: https://hosted.weblate.org/translate/vanilla-os/installer/en/?checksum=5dffd7527f0ef327
> Fix ellipsis error in Weblate string

- po/vanilla-installer.pot
- vanilla_installer/gtk/progress.ui
Show Console ouput -> Show Console output
Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>
> Fix typo in string

- abroot-adapter
This PR ships our custom grub defaults during installation so we don't need to hardcode it for every transaction in ABroot.
I also ran a formatter through the file for the sake of readability. The actual modifications are only in the second commit.
> Ship custom grub default

- vanilla_installer/main.py
Fix css-provider getting too many arguments
http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/CssProvider.html#Gtk.CssProvider.load_from_data
> fix: fix a bug in provider.load_from_data

- po/ro.po
* Some instructions need to be more professional
* Other strings require a correct use of quotes
* Some explanations need to be more clear
> RO Language Updates

- po/POTFILES
- po/vanilla-installer.pot
- vanilla_installer/gtk/default-disk.ui
- vanilla_installer/gtk/default-network.ui
- vanilla_installer/gtk/wireless-row.ui
- Fixed translatable strings in UI files.
- Added new components and panels to POTFILES.
- Updated Strings in the POT file.
> cleanup: update translation files

- vanilla_installer/defaults/keyboard.py
- vanilla_installer/gtk/default-disk.ui
- vanilla_installer/gtk/default-keyboard.ui
- vanilla_installer/gtk/default-language.ui
- vanilla_installer/gtk/default-network.ui
- vanilla_installer/gtk/default-timezone.ui
- re added icons 
- re added description
- removed print from keyboard
> re-add icons and desc

- vanilla_installer/utils/processor.py
Matches behavior of ABRoot. See: https://github.com/Vanilla-OS/ABRoot/pull/158
You can test it here: https://github.com/taukakao/vanilla-installer/releases/tag/systemdmounts
(tested in a VM both encrypted and unencrypted)
> feat [close #310]: makes use of systemd mount units

- vanilla_installer/defaults/network.py
This PR fixes a race condition that happened when connecting to a wireless network while an automatic refresh was underway.
Closes #303
> fix:[close #303] race condition on network refresh

- vanilla_installer/core/disks.py
- vanilla_installer/utils/processor.py
Fixes #376 
This is an alternate solution to #377 trying to be as minimal as possible and avoiding regex. 
Tested successfully in a VM.
> fix[close #376]: Removes call to lsblk for disk that doesn't exist

- vanilla_installer/utils/processor.py
Closes #380 . Tested on a fresh VM.
> fix: Add esp flag to EFI partition

- vanilla_installer/defaults/keyboard.py
- vanilla_installer/utils/processor.py
- vanilla_installer/views/confirm.py
> feat:[close #349] Feature Request: Let choose multiple keyboard layouts

- vanilla_installer/utils/processor.py
Must be merged with https://github.com/Vanilla-OS/core-image/pull/56
> feat: add lsm=integrity

- recipe.json
- vanilla_installer/defaults/disk.py
> Increase minimum disk size to 51200 MiB (50 GiB)

- recipe.json
- vanilla_installer/defaults/disk.py
- vanilla_installer/gtk/widget-partition.ui
> feat[#314]: Tell user about minimum partition sizes

- recipe.json
- vanilla_installer/defaults/nvidia.py
- vanilla_installer/utils/processor.py
This PR makes the installer pick the right image based on the hardware, tested on a laptop with a GTX 1660, the right image was selected automatically (`nvidia-image`).
> feat: support new nvidia images

- recipe.json
- vanilla_installer/defaults/nvidia.py
- vanilla_installer/utils/processor.py
read here: https://github.com/Vanilla-OS/nvidia-image/pull/49
> revert: nvidia multi images support

- vanilla_installer/defaults/network.py
This is because the Network Manager window was crashing the installer at random times.
Fixes #301
> fix [#301]: replaces Network Manager window with gcc

- vanilla_installer/utils/processor.py
This makes the installer compatible with the latest image again.
> fixes missing grub-mkconfig

- vanilla_installer/defaults/disk.py
> feat: create confirm modal for manual partitioning

- vanilla_installer/gtk/widget-partition.ui
This option currently breaks the install.
Closes #451
> close [#451]: hides swap option

- vanilla_installer/utils/processor.py
Follow up for https://github.com/Vanilla-OS/Albius/pull/92
Fixes #460 
Fixes #463 
Fixes #420
> adjusts grub-install for new albius

- vanilla_installer/utils/processor.py
While testing, I noticed that it failed because Disk expects just the disk and not the path with /dev
> fix incorrect path
