Vanilla-OS/vanilla-installer

vanilla_installer/gtk/progress.ui, vanilla_installer/main.py, vanilla_installer/views/progress.py
- atm, `Source Code Pro` fonts are not available in repos, so using `Ubuntu Mono` as placeholder Pango Font.
- get `color-scheme` to apply vte `bg` and `fg` colors
| light | dark |
| ------ | ------ |
| ![Screenshot from 2022-11-19 18-44-29](https://user-images.githubusercontent.com/54065734/202866970-905855f0-e7be-44a5-bb32-6c4d8cce9d23.png) | ![Screenshot from 2022-11-19 18-46-36](https://user-images.githubusercontent.com/54065734/202866979-5a7946d2-f92e-4861-acbf-44e94a2e5305.png) |
=> set_font in vte

vanilla_installer/core/timezones.py
Distinst doesn't recognize timezones with a country name between region and city, like `America/Argentina/Buenos_Aires`. Instead, it uses only region + city for all timezones. When Distinst cannot correctly parse a timezone, for some unbeknownst reason, it refuses to partition the disk, leading to an error during `post_install` on our end.
This shouldn't break the timezone patch from @mirkobrombin since `/usr/share/zoneinfo` already has links for these city names (e.g. `/usr/share/zoneinfo/America/Buenos_Aires` links to `/usr/share/zoneinfo/America/Argentina/Buenos_Aires`.
=> Correct timezone codes for Distinst

vanilla_installer/defaults/timezone.py
Replaces `_` in city names with ` `, so they look better when selecting a timezone (e.g. "New_York" becomes "New York")
This doesn't affect the parameters passed to `distinst` because the script already uses index numbers to retrieve the timezone code, so we're effectively only changing the display name.
=> timezone: remove underscore in city names

README.md, debian/control, vanilla_installer/core/timezones.py, vanilla_installer/defaults/timezone.py
This function adds a request network interface, and tries to get the current time zone through the network interface. This requires the installer to have a network, and when there is no network, the original solution will be tried.
This may cause, in the worst case, the UI display is blocked for 3s
=> feat: add get_timezone_by_ip()

README.md
I had to install that package in order to get vanilla-installer working on my Debian 12.
=> Adds libvte to the dependencies

vanilla_installer/layouts/preferences.py, vanilla_installer/views/confirm.py, vanilla_installer/views/progress.py, vanilla_installer/windows/main_window.py
If these strings are translated these signals would not be emitted/caught, so we shouldn't mark these strings translatable.
=> fix: Do not make signal names translatable

vanilla_installer/views/progress.py
during the installation inside terminal log do not allow the user to do input interrupt.
=> fix: disable input in terminal mode

vanilla_installer/defaults/language.py, vanilla_installer/gtk/default-language.ui, vanilla_installer/gtk/widget-language.ui, vanilla_installer/vanilla-installer.gresource.xml
- changed the layout of welcome screen to better align with [vanilla installer mockup](https://github.com/Vanilla-OS/mockups/issues/2)
- screen shots:
| default state | search state | 
| ------------------- |---------------------- |
| ![Screenshot from 2023-08-28 10-48-00](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/4ad8330b-8b27-4de7-b3b7-381b0f096240) | ![Screenshot from 2023-08-28 10-48-08](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/2c7bd5da-fec6-4349-99d2-588ddf28096c)
_Note: Please dont merge this yet, would be better to merge once keyboard and Timezone page are also adapted_
=> update the look of language/locale screen

vanilla_installer/defaults/timezone.py, vanilla_installer/gtk/default-timezone.ui, vanilla_installer/gtk/widget-timezone.ui, vanilla_installer/vanilla-installer.gresource.xml
- changed the layout of welcome screen to better align with [vanilla installer mockup](https://github.com/Vanilla-OS/mockups/issues/2)
- screenshots:
| default state | search state | 
| ------------------- |---------------------- |
| ![image](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/3514e118-197e-4947-8ce4-902e22ff57d2) | ![image](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/d4a78dc0-4f19-4070-afb0-69114a7d20fb) |
closes #255
=> update the look of timezone screen

vanilla_installer/defaults/network.py
According to PyGObject's [documentation](https://lazka.github.io/pgi-docs/#GLib-2.0/functions.html#GLib.idle_add):
> If the function returns [GLib.SOURCE_REMOVE](https://lazka.github.io/pgi-docs/GLib-2.0/constants.html#GLib.SOURCE_REMOVE) or [False](https://docs.python.org/3/library/constants.html#False) it is automatically removed from the list of event sources and will not be called again.
What I think was happening is that, by not providing a return value, GLib tried to invoke the function again, even after it had been disposed by Python's garbage collector, causing a crash. I left the installer open for quite some time and couldn't reproduce the crash anymore.
=> Fix: Network page crash

vanilla_installer/utils/processor.py
This PR solves the issue where locales would be generated but not properly recognized by the system after installation. We solve this by bind mounting a new locales directory, stored in the mutable part of the system (/var/lib/abroot/etc/vos-a/locales), into the original locales directory in /usr/lib. This mount is done in the same way as /home and /opt, which are mounted via Systemd unit.
=> Fix: Broken locales after installation

vanilla_installer/defaults/keyboard.py, vanilla_installer/defaults/language.py, vanilla_installer/defaults/timezone.py, vanilla_installer/gtk/default-keyboard.ui, vanilla_installer/gtk/default-language.ui, vanilla_installer/gtk/default-timezone.ui
- set the `btn_next` sensitive state when carousel page-changed.
- set the values in selected_group if current_values are present
- added verify_check to `language`, `timezone` similar to the one already present in `keyboard` 
- matched the `test_entry` clamp max-size to `all_keyboard_group` width
=> fix: set the sensitive state for `btn_next`

vanilla_installer/gtk/window.ui
- drop `flat` style in `AdwApplicationWindow` and use `AdwToolbarView`
| default state | scrolled-up state | 
| ------------------ | ------------------------- |
|![image](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/cb35bca2-a29e-4209-9f12-5e386a3f8db4) |![image](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/9ba43e77-029f-402b-9c9f-135b63134e43) |
_changes: in default state it uses `flat` and when scrolled up for content it shows separator after `AdwHeaderBar`_
=> update to `AdwToolbarView`

recipe.json, vanilla_installer/defaults/conn_check.py, vanilla_installer/gtk/default-keyboard.ui
- fix: #315 
- added `hexpand` and `vexpand` properties
| before | after |
| -----------|------- |
| ![image](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/c0920b9d-4c1e-4c32-9dbd-a87779eabd97)  |![image](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/976881a6-6c88-4da2-88b3-32a41c65a539) |
- fix: #317
- moved _Language_, _Keyboard_ pages before network related pages.
=> fix #315 and #317

vanilla_installer/views/progress.py
- do not depend on `color-scheme` enum, instead make use of `AdwStyleManager`
[Screencast from 2023-12-24 15-23-55.webm](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/2593f13b-41ca-4a57-bbd6-b627895a3110)
[Screencast from 2023-12-24 15-25-15.webm](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/2c6f1cbe-6e9d-4781-9de0-a4757477735e)
closes: #325
=>  fix: sync vte-terminal colors on change of `color-scheme`:

vanilla_installer/core/timezones.py, vanilla_installer/defaults/timezone.py, vanilla_installer/gtk/default-timezone.ui
This PR reworks the timezone UI to better display city names, separated by country.
Closes #212
=> feat: [close #212] Improve timezone names

vanilla_installer/core/disks.py, vanilla_installer/defaults/disk.py, vanilla_installer/gtk/dialog-disk-confirm.ui, vanilla_installer/utils/processor.py
The installer was not able to install over an old install of vanilla because of LVM. 
Fixes #370   Fixes #369  Fixes #368
=> fix [#370 #369 #368]: Remove conflicting LVM objects

vanilla_installer/core/timezones.py, vanilla_installer/defaults/disk.py, vanilla_installer/defaults/network.py, vanilla_installer/defaults/timezone.py, vanilla_installer/defaults/welcome.py, vanilla_installer/windows/main_window.py
This PR attempts to improve startup time by adding extra async tasks for some expensive functions.
EDIT: Also fixed some formatting :)
=> fix: Startup time + stuttering

vanilla_installer/defaults/network.py
Use the NM UUID generate function to avoid UUID pointer assertion error
The function is documented [here](https://lazka.github.io/pgi-docs/#NM-1.0/functions.html#NM.utils_uuid_generate).  Tested this locally and it seems to work without issue.
Can I get someone else to test and confirm?
=> fix[#301]: Generate UUID with NM

vanilla_installer/utils/processor.py
Since abroot now mounts everything before systemd, these configurations are not needed anymore.
The systemd mount points or the fstab don't break anything so this PR is just an enhancement.
Depends on:
https://github.com/Vanilla-OS/core-image/pull/63
don't merge before it
A complete install was tested with these changes. It installed fine and was also able to perform an upgrade afterwards.
=> Adjust for new abroot

vanilla_installer/utils/processor.py
This ensures that there is a valid configuration in /usr
For details, see https://github.com/Vanilla-OS/ABRoot/pull/319
=> saves configuration in usr

vanilla_installer/utils/processor.py
This is necessary to have the correct keyboard set in the initramfs.
This is definitely not the optimal solution. That would probably involve creating a post operation that creates the initramfs and removing the step from a regular install altogether. 
I've tried it and it would require a lot of changes in Albius and vanilla-installer so I think it's way out of scope for this bugfix. 
Fixes #392 
Tested in a VM.
=> fix [#392]: moves generation of initramfs

vanilla_installer/defaults/disk.py, vanilla_installer/gtk/widget-partition.ui, vanilla_installer/utils/processor.py
This PR adds an option to keep the EFI partition during install. As of now, the only indication that it works is through VANILLA_FAKE's JSON dump. This has not yet been tested on a Vanilla OS system without VANILLA_FAKE.
This PR works like this:
- The manual partitioning page has a toggle to keep the EFI partition. This toggle sets the fstype of the EFI partition to 'unformatted'.
- The processor skips adding the format option of any partition that has the 'unformatted' fstype. Note that the mountpoint is added before the return statement so that the EFI file can still be added.
I would like to stress again that this has not yet been tested on a live system. If I get the time, I will do it later. Any independant tests would be appreciated to make sure that there are no unexpected …
=> feat:[#306] Have option to not format EFI partition

vanilla_installer/utils/processor.py
This writes the correct config for abroot after this change:
https://github.com/Vanilla-OS/ABRoot/pull/324
It's not strictly necessary yet but I think it should be added for consistency.
=> adapts config to new abroot version

vanilla_installer/defaults/conn_check.py, vanilla_installer/defaults/disk.py, vanilla_installer/defaults/encryption.py, vanilla_installer/defaults/image.py, vanilla_installer/defaults/keyboard.py, vanilla_installer/defaults/language.py, vanilla_installer/defaults/network.py, vanilla_installer/defaults/nvidia.py, vanilla_installer/defaults/theme.py, vanilla_installer/defaults/timezone.py, vanilla_installer/defaults/vm.py, vanilla_installer/defaults/welcome.py, vanilla_installer/views/confirm.py, vanilla_installer/views/done.py, vanilla_installer/views/progress.py, vanilla_installer/windows/main_window.py
First off, if I'm using the wrong term, it's not my fault. It's all Mirko (/j)
This PR improves the performance and almost entirely removes the lag in the installer. The way it does this is by rendering all the pages without the huge lists of the checkboxes for the pages like Language.
Now for the technical explanation:
When the app starts, the builder runs. This runs the entire `__init()` function of each page before the app starts. The rendering of these huge lists of checkboxes - or at least, adding them to GTK's list of widgets - is done before the app even starts. This means that GTK has to take care of 1000+ widgets, most of which aren't always used, and end up causing lagging even on the most basic of pages.
This PR moves the functionality of adding these widget lists to GTK's list …
=> Improve the performance by implementing Deltas

vanilla_installer/defaults/image.py
The regex we currently use to verify the url for a custom image is too complicated and doesn't work properly, this new regex is a lot shorter and properly matches urls
closes #433
=> fix: [close #433] use better custom image url regex

vanilla_installer/utils/processor.py
LVM would sometimes be missing space due to alignment taking up extra space.
While the 100 MiB are definitely not rigorous I think it's a good balance between taking up unnecessary space and actually fixing this problem for good.
Fixes #439
=> fix [#439]: changes the partition sizes

vanilla_installer/defaults/disk.py, vanilla_installer/utils/processor.py
Not entirely accurate: It's more of an option to format it as 'unformatted':
=> feat[#293]: Add "Do not format" toggle for /var partition in manual partitioning

vanilla_installer/utils/processor.py
This is to avoid blocking id 1000, since that should go the first user.
Fixes #440 
Requires https://github.com/Vanilla-OS/Albius/pull/87
=> fix [#440]: set uid of vanilla user

vanilla_installer/defaults/language.py
- emit parent verify language
closes #426
=> fix: enable language next button on first click

vanilla_installer/core/disks.py, vanilla_installer/defaults/disk.py
This adds an option to show removable drives.
Tested on hardware with two USB sticks.
=> fix [#348]: adds button to show removable disks

vanilla_installer/defaults/disk.py, vanilla_installer/utils/processor.py
There wasn't enough space in the init partition to contain three copies of the kernel and initramfs, which was necessary for abroot upgrades. 
Changing this might allow us to be more flexible in the future with better solutions.
=> fix init partition being too small to contain all necessary data

vanilla_installer/utils/processor.py
ABRoot expects /.system/opt to exist and the installer moves it into var. 
Also, some other things were outdated.
=> Fix abroot issue

vanilla_installer/main.py
check if the ignore env vars are set before checking if the hardware meets requirements.  this allows users to bypass the hardware checks with the ignore vars by checking them first without verifying the hardware
relates #461
=> fix:[#461] reorder ignore hw checks

debian/control
This package does not contain any binary files, so the `architecture` should be set to `all` to mark it as architecture-independent.
Related to https://github.com/Vanilla-OS/live-iso/issues/87.
=> debian: fix architecture
